#!/usr/bin/env python3
"""Regression test for the clean Overleaf ZIP exporter.

The test extracts the production helper into a disposable shell process and
checks its observable contract without contacting the remote server.
"""

from __future__ import annotations

import shutil
import subprocess
import tempfile
import zipfile
from pathlib import Path


REQUIRED_PATHS = (
    "main.tex",
    "README.md",
    "references.bib",
    "sections/methods.tex",
    "sections/experiments.tex",
    "sections/results.tex",
    "sections/data_availability.tex",
    "figures/figure_1_method_schematic.pdf",
    "figures/figure_2_baselines.pdf",
    "figures/figure_3_ablation.pdf",
    "source_data/fold_metrics.csv",
    "source_data/summary_metrics.csv",
    "source_data/paired_wilcoxon_statistics.csv",
    "source_data/dataset_manifest.json",
    "source_data/environment_manifest.json",
    "tables/fold_metrics.csv",
    "tables/summary.csv",
    "tables/coverage.csv",
    "figure_legends.txt",
    "generated/results_autogenerated.tex",
    "generated/abstract_autogenerated.tex",
    "generated/discussion_autogenerated.tex",
    "generated/conclusion_autogenerated.tex",
    "generated/protocol_autogenerated.tex",
)


def production_helper(repository: Path) -> str:
    script = (repository / "finalize_overleaf_package.sh").read_text(encoding="utf-8")
    start = script.index("write_overleaf_zip() {")
    end = script.index("\nif (( CHECK_LOCAL_PLACEHOLDERS ))", start)
    return script[start:end]


def main() -> None:
    repository = Path(__file__).resolve().parent
    source_main = repository / "manuscript" / "main.tex"
    source_readme = repository / "manuscript" / "README.md"
    source_bib = repository / "manuscript" / "references.bib"
    source_pdf = repository / "manuscript" / "figures" / "figure_1_method_schematic.pdf"

    with tempfile.TemporaryDirectory(prefix="dti-overleaf-zip-test-") as temp_dir:
        root = Path(temp_dir)
        manuscript = root / "manuscript"
        manuscript.mkdir()
        shutil.copy2(source_main, manuscript / "main.tex")
        shutil.copy2(source_readme, manuscript / "README.md")
        shutil.copy2(source_bib, manuscript / "references.bib")
        (manuscript / "figures").mkdir()
        shutil.copy2(source_pdf, manuscript / "figures" / "figure_1_method_schematic.pdf")
        for relative_path in REQUIRED_PATHS:
            path = manuscript / relative_path
            path.parent.mkdir(parents=True, exist_ok=True)
            if path.exists():
                continue
            if path.suffix == ".pdf":
                shutil.copy2(source_pdf, path)
            else:
                path.write_text("fixture\n", encoding="utf-8")

        (manuscript / "build").mkdir()
        (manuscript / "build" / "must-not-ship.txt").write_text("no\n", encoding="utf-8")
        (manuscript / "build_preflight_fixture").mkdir()
        (manuscript / "build_preflight_fixture" / "must-not-ship.txt").write_text(
            "no\n", encoding="utf-8"
        )

        output_zip = root / "release" / "dti-overleaf.zip"
        shell_code = "\n".join(
            (
                "set -euo pipefail",
                f"LOCAL_ROOT={str(manuscript)!r}",
                production_helper(repository),
                f"write_overleaf_zip {str(output_zip)!r}",
            )
        )
        first = subprocess.run(
            ["bash", "-c", shell_code],
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )
        if first.returncode != 0 or "OVERLEAF_SOURCE_ZIP_COMPLETE" not in first.stdout:
            raise AssertionError(f"ZIP export failed:\n{first.stdout}")
        if not output_zip.is_file():
            raise AssertionError("ZIP export did not create its destination")

        with zipfile.ZipFile(output_zip) as archive:
            names = set(archive.namelist())
        prefix = "ArnoldiGCL-S1-S2-DTI/"
        expected = {prefix + path for path in REQUIRED_PATHS}
        if not expected.issubset(names):
            raise AssertionError(f"ZIP is missing required files: {sorted(expected - names)}")
        if any("/build/" in name or "/build_preflight_fixture/" in name for name in names):
            raise AssertionError("ZIP included a local build directory")

        second = subprocess.run(
            ["bash", "-c", shell_code],
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )
        if second.returncode == 0 or "Refusing to overwrite" not in second.stdout:
            raise AssertionError(f"ZIP overwrite protection failed:\n{second.stdout}")

        missing_artifact = manuscript / "generated" / "protocol_autogenerated.tex"
        missing_artifact.unlink()
        incomplete_zip = root / "release" / "incomplete-overleaf.zip"
        incomplete_shell_code = "\n".join(
            (
                "set -euo pipefail",
                f"LOCAL_ROOT={str(manuscript)!r}",
                production_helper(repository),
                f"write_overleaf_zip {str(incomplete_zip)!r}",
            )
        )
        incomplete = subprocess.run(
            ["bash", "-c", incomplete_shell_code],
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )
        if incomplete.returncode == 0 or "Audited manuscript artifact is missing" not in incomplete.stdout:
            raise AssertionError(f"Missing-artifact protection failed:\n{incomplete.stdout}")
        if incomplete_zip.exists():
            raise AssertionError("Incomplete manuscript unexpectedly created a ZIP")

    print("OVERLEAF_ZIP_EXPORT_REGRESSION_PASS")


if __name__ == "__main__":
    main()
