#!/usr/bin/env python3
"""Regression test for the local finalizer placeholder gate.

The finalizer must ignore source-only fallback TODOs protected by
``\IfFileExists`` while still refusing a manuscript whose author/declaration or
release metadata has not been supplied.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


FRAGMENTS = (
    "results_autogenerated.tex",
    "abstract_autogenerated.tex",
    "discussion_autogenerated.tex",
    "conclusion_autogenerated.tex",
    "protocol_autogenerated.tex",
)


def run_gate(repository: Path, manuscript: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [
            "bash",
            str(repository / "finalize_overleaf_package.sh"),
            "--local-root",
            str(manuscript),
            "--check-local-placeholders",
        ],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )


def replace_once(path: Path, old: str, new: str) -> None:
    text = path.read_text(encoding="utf-8")
    if old not in text:
        raise AssertionError(f"Expected placeholder not found in {path}: {old}")
    path.write_text(text.replace(old, new, 1), encoding="utf-8")


def main() -> None:
    repository = Path(__file__).resolve().parent
    with tempfile.TemporaryDirectory(prefix="dti-finalizer-gate-") as temp_dir:
        manuscript = Path(temp_dir) / "manuscript"
        shutil.copytree(
            repository / "manuscript",
            manuscript,
            ignore=shutil.ignore_patterns("build", "build_*", "generated", "source_data", "tables"),
        )
        generated = manuscript / "generated"
        generated.mkdir()
        for filename in FRAGMENTS:
            (generated / filename).write_text("% synthetic generated fragment\n", encoding="utf-8")

        blocked = run_gate(repository, manuscript)
        if blocked.returncode == 0 or "Publication metadata or release identifiers" not in blocked.stdout:
            raise AssertionError(f"Unfilled publication metadata did not block finalization:\n{blocked.stdout}")

        main_tex = manuscript / "main.tex"
        replace_once(main_tex, r"\author{\todo{Authors and affiliations to be supplied}}", r"\author{Test Author}")
        replace_once(main_tex, r"\textbf{Author contributions.} \todo{To be completed by the authors.}", r"\textbf{Author contributions.} Test Author: Conceptualization, software and writing.")
        replace_once(main_tex, r"\textbf{Competing interests.} \todo{To be completed by the authors.}", r"\textbf{Competing interests.} The author declares no competing interests.")
        availability = manuscript / "sections" / "data_availability.tex"
        replace_once(availability, r"\todo{repository name and persistent identifier}", r"https://doi.org/10.0000/example")
        replace_once(availability, r"\todo{code repository and commit or release tag}", r"https://example.org/repository/releases/tag/v1.0.0")

        passed = run_gate(repository, manuscript)
        if passed.returncode != 0 or "LOCAL_PLACEHOLDER_GATE_COMPLETE" not in passed.stdout:
            raise AssertionError(f"Inactive fallback TODOs incorrectly blocked finalization:\n{passed.stdout}")
    print("FINALIZER_PLACEHOLDER_GATE_REGRESSION_PASS")


if __name__ == "__main__":
    main()
