#!/usr/bin/env python3
"""Guard the release-finalizer ordering contract.

The first remote actions must be read-only audits.  Release-time manifest
writes and downstream aggregation are allowed only after those audits pass.
"""

from pathlib import Path


def main() -> None:
    script = Path(__file__).with_name("finalize_overleaf_package.sh").read_text(
        encoding="utf-8"
    )

    split_call = 'remote_ssh_with_marker "SPLIT_INTEGRITY_COMPLETE"'
    result_call = 'remote_ssh_with_marker "FINAL_AUDIT_COMPLETE"'
    process_gate = "Confirming no training or background release process remains"
    dataset_write = 'echo "[4/10] Writing the pinned remote dataset-provenance manifest"'
    runtime_write = 'echo "[5/10] Writing the remote runtime manifest"'
    aggregate = 'echo "[6/10] Aggregating the audited fold metrics"'

    positions = [
        script.index(process_gate),
        script.index(split_call),
        script.index(result_call),
        script.index(dataset_write),
        script.index(runtime_write),
        script.index(aggregate),
    ]
    if positions != sorted(positions):
        raise AssertionError(f"Release steps are out of order: {positions}")

    for process_pattern in (
        "[r]un_drugban_queue\\\\.sh",
        "[r]un_drugban_fold\\\\.py",
        "[p]ostprocess_after_drugban\\\\.sh",
    ):
        if process_pattern not in script:
            raise AssertionError(f"Concurrent-process guard is missing {process_pattern}")
    if "Concurrent DrugBAN or release process remains; refusing to finalize." not in script:
        raise AssertionError("Concurrent-process guard does not fail closed")
    marker_helper = script.index("remote_ssh_with_marker()")
    if marker_helper > positions[1]:
        raise AssertionError("Marker helper is defined after the first audit call")
    for marker in (
        'remote_ssh_with_marker "SPLIT_INTEGRITY_COMPLETE"',
        'remote_ssh_with_marker "FINAL_AUDIT_COMPLETE"',
    ):
        if marker not in script:
            raise AssertionError(f"Required audit marker gate is missing: {marker}")

    for artifact in (
        'figure_2_baselines.$extension',
        'figure_3_ablation.$extension',
        'fold_metrics.csv summary_metrics.csv paired_wilcoxon_statistics.csv dataset_manifest.json environment_manifest.json',
        'fold_metrics.csv summary.csv coverage.csv',
        'figure_legends.txt',
        'results_autogenerated.tex abstract_autogenerated.tex discussion_autogenerated.tex conclusion_autogenerated.tex protocol_autogenerated.tex',
    ):
        if artifact not in script:
            raise AssertionError(f"Finalizer artifact synchronization is missing: {artifact}")

    dataset_definition = script.index("remote_dataset_manifest=(")
    if dataset_definition < positions[1]:
        raise AssertionError("Dataset manifest command is defined before result audit")

    print("FINALIZER_RELEASE_ORDER_REGRESSION_PASS")


if __name__ == "__main__":
    main()
